### ISSUE TITLE
License

### ISSUE THREAD

**Issue by davidgraeff** [Loki-Astari/Examples#1]
Would you mind adding a LICENSE to your code? So that it is clear if your well designed wrapper classes can be used.
And if it is a liberal license, would you please add your name and copyright line to each file?

Cheers

**Comment by Loki-Astari** [comment]
Please create a pull request with an appropriate license file.

Don't add comments to the code. I want the code to be identical to the some articles I am writing and having that type of comment in the article would be distracting from the point.

**Comment by davidgraeff** [comment]
The licence file is not enough unfortunately. It is two lines in front of each file, that you don't need to copy to an article at all. Something like:
```
Licensed under the MIT License. See attached License file.
Copyright (C) 2018 Your Name
```

**Comment by Loki-Astari** [comment]
I added the appropriate MIT License at the root of the project.

Note all this code has been reviewed on https://CodeReview.stackexchange.com . One of the requirements of the site is that all code on the site is available via [CC license](https://creativecommons.org/licenses/by-sa/3.0/). So you can also get the code from there:

[C Socket: Part 4](https://codereview.stackexchange.com/q/131211/507)
[C Socket: Part 3](https://codereview.stackexchange.com/q/131190/507)
[C Socket: Part 2](https://codereview.stackexchange.com/q/131137/507)
[C Socket: Part 1](https://codereview.stackexchange.com/q/131136/507)

**Comment by davidgraeff** [comment]
Thanks :)
